favicon: null
name: stevenstarfas
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0
  rhythmicContrast: 1
  brandColors:
    - '#d9d1c4'
    - '#252525'
    - '#c3a084'
    - '#96644b'
    - '#863627'
  lightness: 1
typography_spectrum: 0.60482
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5501792
analytics:
  twitter: null
  google: null
  facebook: null
