name: stevenstarfas
favicon: null
layout_spectrum: 0.43719321046955884
typography_spectrum: 0.5811108921188861
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3616344705224037
  lightness: 0.40828605415299535
  saturation: 0.37742350716143847
  rhythmicContrast: 0.8306476844009012
purpose: []
