layout_spectrum: 0.8389982716180384
typography_spectrum: 0.17646526033058763
color:
  saturation: 0.6753495328593999
  brandStrength: 0.6718723271042109
  rhythmicContrast: 0.5445689333137125
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.6796809956431389
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
name: stevenstarfas
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: IN A MIRROR
description: SEEN DIMLY
purpose: []
