name: stevenstarfas
favicon: null
layout_spectrum: 0.75108
typography_spectrum: 0.60482
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9d1c4'
    - '#252525'
    - '#c3a084'
    - '#96644b'
    - '#863627'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
